GET http://localhost:8000

###
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
   "email": "test3@gmail.com",
   "password": "123456"
}

###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
   "email": "test3@gmail.com",
   "password": "123456"
}

###
GET http://localhost:8000/api/v1/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAsImVtYWlsIjoidGVzdDNAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjMiLCJpYXQiOjE3NDU3NDgxMjAsImV4cCI6MTc0NjE4MDEyMH0.q8Z7Ov6rbfnfb5cqxWGPQB9AC0c-76Kbw9sJHNbTBbk

###
GET http://localhost:8000/api/v1/insert/category

###
GET http://localhost:8000/api/v1/insert/book

###
GET http://localhost:8000/api/v1/books/?sort=desc&limit=2&name=music

###
GET http://localhost:8000/api/v1/books?sort=desc&available=10,20
